### ISSUE TITLE
Practice Exam Results message

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#231]
## Issue Type 
- [x] Incorrect content

## Description
The message students receive upon completion of the practice exam does not provide correct instructions. New text and student guidance needs to be provided. 
![Practice Exam Results](https://user-images.githubusercontent.com/31414225/61313604-c613e080-a7c8-11e9-9322-6eb104d7f71c.png)

## Location
Trusted Tester course Practice Exam results message
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=159&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=2

## Actual Behavior / Observation

- Instructor help is not provided.
- Course name is not properly referenced.

## Expected Behavior / Recommendation
Instructions needs to be developed that direct students to the Q&A sessions.
New wording needs to be provided to Carney.

**Comment by mikebarklage** [comment]
I made some of the more obvious updates to the Scoring page text, but still need the finalized version.

**Comment by Tonylayton1** [comment]
Moving to "To-Do" since this needs text from DHS

**Comment by AnnMarieDavis** [comment]
Revise both the "Nice Try" and "Congratulations" email messages as specified in the attachments.
[Congratulations Practice.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3436149/Congratulations.Practice.docx)
[Nice Try Revision Practice.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3436150/Nice.Try.Revision.Practice.docx)

**Comment by mikebarklage** [comment]
There's more than I expected here, so it's taking some time to convert it into HTML, then convert that into something JS can handle. I'm working on it.

**Comment by mikebarklage** [comment]
OK, done.

**Comment by mikebarklage** [comment]
I just updated it so hopefully the new img link isn't broken in emails - my web email reader just gives me the alt text, but let me know how it looks on other devices.

**Comment by Tonylayton1** [comment]
Issue with the failure message. It is correct the first 2 times, but when the user fails a third time, the message changes. I think there is still code telling the message to change after three tries, even though there is no longer a limit on tries.

**Comment by Tonylayton1** [comment]
The passing message is working as well, except that the email links don't work in either the course or the email that gets sent. 

To summarize the 2 issues:
If user fails 3 times, the failure message changes
email hyperlinks found in the fail and pass messages do not work

**Comment by mikebarklage** [comment]
I believe this is fixed now.

**Comment by Tonylayton1** [comment]
The number of attempts issue is verified on dev.

3 issues remain: 
The email links still don't work 
The images (as mike predicted) do not show up on the email
When the student revisits a completed exam and the results screen is shown, it is not displaying correctly. 

I will open 3 separate issues on this so that this issue can be closed.

**Comment by AnnMarieDavis** [comment]
1. The images would be very nice to have, but we can leave those off if they prove too problematic....
1. However, the integrity of the message after 3 fails is crucial.... 
1. The email links really should to work (but if needed, a workaround that provides just the address is possible)

**Comment by AnnMarieDavis** [comment]
Wording looks great and I did see the image in the message
http://52.23.182.152/dhsv5/scormapi/lesson1.php?SCOInstanceID=159&studentName=Ann%20Marie%20Davis&ltiUserId=123&studentEmail=annmarie.davis@associates.hq.dhs.gov&examId=2

The email link also worked for me - though the Subject line did not populate with the one in the link provided.

Also there are open bullets (look like a circle outlined) rather than solid bullets on the email.  Since some screenreaders do not read open bullet properly, please substitute with solid black bullets.

All of this was in the message that was displayed within the course.  I did not actually receive an email message (yet?!) with this information

**Comment by mikebarklage** [comment]
I always get the subject line Post OFTE 251 Exam Review, which itself is probably no longer accurate.

**Comment by mikebarklage** [comment]
Updated.

**Comment by Tonylayton1** [comment]
the email subject line says exam. can the practice, exam, and incrementals have different subject lines?

**Comment by mikebarklage** [comment]
Yes, but I'd have to pass a new variable into the PHP script that sends the email. Probably an enhancement for after deployment.

**Comment by mikebarklage** [comment]
(Also, emails shouldn't be sent for Incrementals.)

**Comment by Tonylayton1** [comment]
As per Andrew, lets make them generic. just remove "Cerification" from the subject line

**Comment by mikebarklage** [comment]
Done.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
I still see the bullet on the page are styled as open bullets, but the core of the message is correct.  OAST will accept this as is. Closed.
