### ISSUE TITLE
revisiting exam that has been passed

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#287]
when I have passed the exam, the results screen shows up correctly, but when I exit the exam and revisit it (which takes me straight to the results screen) the results are not displaying correctly. 

-The missed IDs table is not showing up
-The contents of the results screen are bleeding out of the white area down into the blue

**Comment by Tonylayton1** [comment]
![image](https://user-images.githubusercontent.com/52048615/62244680-eee1cb80-b3ad-11e9-808c-49726bc2f74d.png)

**Comment by Tonylayton1** [comment]
Summary looks fine upon initially passing the course, but if I exit and reopen the module, the final screen looks like the screenshot above.

**Comment by mikebarklage** [comment]
When I passed the Final exam then reopened it, I didn't get a new exam or the success page, I just got a page with the DHS header and no content. Is anyone else seeing that or just me?

**Comment by Tonylayton1** [comment]
One of the students saw the issue I was seeing upon initially arriving on the final screen. This is much more serious than what I was experiencing so I'll need to try and replicate it.

**Comment by mikebarklage** [comment]
I think I've fixed the "no content" problem, or at least taken a step towards it.

When the exam was in a "passed" state, it was trying to load a Success HTML page (from v4) that no longer exists. I removed that, and now it just reloads the scoring page - and re-scores the exam, and re-sends the email.

Before I try to fix the Incorrect ID table that still isn't appearing (and I know 3 days before deployment is a great time to ask this), what do we actually WANT the exam to do in the "passed" state? Now that I know where to look, we might be able to do something different. Or we can leave it as is.

**Comment by mikebarklage** [comment]
My above comment should've been on the JIRA item for Final, btw. So far I see no change in Incremental behavior, haven't tried passing a Practice exam yet.

**Comment by Tonylayton1** [comment]
the same thing is still happening to me. I get the bleed out like in the screenshot above.

**Comment by drewnielson** [comment]
For this one, let's just do the same thing we are doing for the final exam now: send them to a separate page telling them they've already passed.

**Comment by mikebarklage** [comment]
I'll have to do a bit of research - the "completed" state may only apply to the Final exam, so our options may be limited.

**Comment by mikebarklage** [comment]
I updated the way it checks whether the user has passed, and it seems to work for Final and Practice.

Incrementals still just restart the exam for me. Is that what others are seeing?

**Comment by drewnielson** [comment]
The practice exam let me retake the exam with a score between 90 and 100% Once I got 100%, I got the page telling me I had already passed the exam.

The incremental allows me to continue making attempts. I think we can deploy without the incrementals working like the practice for now, but let's see if we can get the incrementals to work the same way. There could be some impact on how the overall course grade is scored if someone makes an unsuccessful attempt after initially passing.

**Comment by drewnielson** [comment]
Also just noticed that the exam admin only displays the first attempt (with a 99% score), but not the second attempt with the correct answer for the Test ID that was incorrect on the first attempt.

**Comment by Tonylayton1** [comment]
This would be the first time a course can be taken again while it's already passed. Very possible the admin page is having difficulty sorting it out.

**Comment by Tonylayton1** [comment]
No longer sends user to first page, instead they land on "no further attempt needed!" - verified on dev

**Comment by drewnielson** [comment]
verified on dev
